export const TALL=0,BLOCKED=3;
// The fenced lawn is 30 x 36 m like the Godot yard. The house runs along the left (-x) fence,
// its porch steps onto the lawn, the patio sits at the front (+z) and three shade trees stand in the grass.
export const YARD={halfX:15,halfZ:18},porch={x:-14.2,z:-4,w:3.2,d:10},patio={x:5,z:15,w:8,d:4},gasCan={x:-12,z:-4},trees=[[12,9],[12,-12],[-12,12]];
export class Lawn {
  constructor(width=YARD.halfX*2,depth=YARD.halfZ*2,cell=.5){this.width=width;this.depth=depth;this.cell=cell;this.cols=Math.ceil(width/cell);this.rows=Math.ceil(depth/cell);this.blocked=new Set();this.reset();}
  center(id){return {x:-this.width/2+(id%this.cols+.5)*this.cell,z:-this.depth/2+(Math.floor(id/this.cols)+.5)*this.cell};}
  block(test){for(let id=0;id<this.cols*this.rows;id++){const p=this.center(id);if(test(p.x,p.z))this.blocked.add(id);}this.reset();}
  reset(){this.cells=new Uint8Array(this.cols*this.rows);for(const id of this.blocked)this.cells[id]=BLOCKED;this.cutCount=0;}
  mow(x,z,radius,stripe=1){const changed=[];for(let row=Math.max(0,Math.floor((z-radius+this.depth/2)/this.cell));row<Math.min(this.rows,Math.ceil((z+radius+this.depth/2)/this.cell));row++)for(let col=Math.max(0,Math.floor((x-radius+this.width/2)/this.cell));col<Math.min(this.cols,Math.ceil((x+radius+this.width/2)/this.cell));col++){const id=row*this.cols+col,p=this.center(id);if(Math.hypot(p.x-x,p.z-z)<=radius&&this.cells[id]===TALL){this.cells[id]=stripe;this.cutCount++;changed.push(id);}}return changed;}
  sweep(from,to,radius,stripe){const steps=Math.max(1,Math.ceil(Math.hypot(to.x-from.x,to.z-from.z)/(this.cell*.5))),out=[];for(let i=0;i<=steps;i++)out.push(...this.mow(from.x+(to.x-from.x)*i/steps,from.z+(to.z-from.z)*i/steps,radius,stripe));return out;}
  get progress(){const total=this.cells.length-this.blocked.size;return total?this.cutCount/total:1;}
  objectives(){const totals=[0,0,0,0],cuts=[0,0,0,0];for(let id=0;id<this.cells.length;id++){if(this.cells[id]===BLOCKED)continue;const {z}=this.center(id),row=Math.floor(id/this.cols),col=id%this.cols,zone=z<-6?2:z>6?0:1;let edge=false;for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++){const xx=col+dx,zz=row+dz;if(xx<0||zz<0||xx>=this.cols||zz>=this.rows||this.cells[zz*this.cols+xx]===BLOCKED)edge=true;}for(const goal of edge?[zone,3]:[zone]){totals[goal]++;if(this.cells[id]!==TALL)cuts[goal]++;}}return totals.map((n,i)=>n?cuts[i]/n:1);}
}
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export const obstacles=[porch,patio,...trees.map(([x,z])=>({x,z,r:.7}))];
export class Game {
 constructor(storage,defaultQuality='high'){this.storage=storage;this.lawn=new Lawn();this.lawn.block((x,z)=>obstacles.some(o=>o.r?Math.hypot(x-o.x,z-o.z)<o.r:Math.abs(x-o.x)<o.w/2&&Math.abs(z-o.z)<o.d/2));this.best=0;this.settings={quality:defaultQuality,muted:false};try{const b=Number(storage?.getItem('lw.babylon.best'));if(Number.isFinite(b)&&b>0)this.best=b;const s=JSON.parse(storage?.getItem('lw.babylon.settings')||'{}');if(['low','medium','high'].includes(s.quality))this.settings.quality=s.quality;if(typeof s.muted==='boolean')this.settings.muted=s.muted;}catch{}this.reset();}
 reset(){this.lawn.reset();this.mower={x:0,z:-8,yaw:0};this.walker={x:0,z:0,yaw:0};this.onMower=true;this.speed=0;this.measuredSpeed=0;this.fuel=1;this.blades=true;this.paused=false;this.finished=false;this.elapsed=0;this.highlight=false;this.message='Make your first pass.';}
 get actor(){return this.onMower?this.mower:this.walker;}
 saveSettings(){try{this.storage?.setItem('lw.babylon.settings',JSON.stringify(this.settings));}catch{this.message='Settings could not be saved.';}}
 fits(x,z,r){return Math.abs(x)<=YARD.halfX-r&&Math.abs(z)<=YARD.halfZ-r&&!obstacles.some(o=>o.r?Math.hypot(x-o.x,z-o.z)<r+o.r:Math.hypot(Math.max(Math.abs(x-o.x)-o.w/2,0),Math.max(Math.abs(z-o.z)-o.d/2,0))<r);}
 mount(){if(this.finished||this.paused)return;if(this.onMower){const a=this.mower;const spots=[[1.3,0],[-1.3,0],[0,-1.5],[0,1.5]];const spot=spots.find(([dx,dz])=>this.fits(a.x+dx,a.z+dz,.2));if(!spot){this.message='Move to an open spot to hop off.';return;}this.walker={x:a.x+spot[0],z:a.z+spot[1],yaw:a.yaw};this.onMower=false;}else if(Math.hypot(this.walker.x-this.mower.x,this.walker.z-this.mower.z)<1.8){this.onMower=true;}else{this.message='Walk closer to your mower to get on.';}this.speed=0;}
 step(dt,input={}){if(this.paused||this.finished){this.measuredSpeed=0;return [];}dt=clamp(dt,0,.05);this.elapsed+=dt;const a=this.actor,old={x:a.x,z:a.z},throttle=clamp(input.throttle||0,-1,1),steer=clamp(input.steer||0,-1,1);if(this.onMower){const target=throttle*(throttle<0?1.5:4)*(this.fuel<=0?.3:1);const delta=target-this.speed;this.speed+=Math.sign(delta)*Math.min(Math.abs(delta),(Math.abs(target)>Math.abs(this.speed)?3:6)*dt);a.yaw+=steer*(1.2+.4*Math.min(Math.abs(this.speed)/1.5,1))*(this.speed<-.1?-1:1)*dt;}else{a.yaw+=steer*2.6*dt;this.speed=throttle*(throttle<0?1.2:2.2);}
 const r=this.onMower?.72:.2,nx=a.x+Math.sin(a.yaw)*this.speed*dt,nz=a.z+Math.cos(a.yaw)*this.speed*dt;if(this.fits(nx,a.z,r))a.x=nx;if(this.fits(a.x,nz,r))a.z=nz;const distance=Math.hypot(a.x-old.x,a.z-old.z);this.measuredSpeed=dt?distance/dt:0;if(this.onMower)this.fuel=Math.max(0,this.fuel-distance/1200*(this.blades?1:.5));if(Math.hypot(this.mower.x-gasCan.x,this.mower.z-gasCan.z)<2.5&&this.measuredSpeed<.1){this.fuel=Math.min(1,this.fuel+.35*dt);this.message='Refuelling by the porch.';}
 const offset=this.onMower?.3:.65,tip=p=>({x:p.x+Math.sin(a.yaw)*offset,z:p.z+Math.cos(a.yaw)*offset});const stripe=(Math.abs(Math.sin(a.yaw))>Math.abs(Math.cos(a.yaw))?Math.sin(a.yaw):Math.cos(a.yaw))>=0?1:2;const changed=(!this.onMower||(this.blades&&distance>.001))?this.lawn.sweep(tip(old),tip(a),this.onMower?.55:.34,stripe):[];if(this.lawn.progress>=.99){this.finished=true;this.speed=0;this.measuredSpeed=0;this.message='Yard complete!';if(!this.best||this.elapsed<this.best){this.best=this.elapsed;try{this.storage?.setItem('lw.babylon.best',String(this.best));}catch{this.message='Yard complete. Record could not be saved.';}}}return changed;}
}
