import {Engine,Scene,Vector3,Color3,Color4,MeshBuilder,StandardMaterial,HemisphericLight,DirectionalLight,ShadowGenerator,ArcRotateCamera,TransformNode,Matrix,Quaternion,DynamicTexture} from '@babylonjs/core';
import './style.css';
import {Game, BLOCKED} from './lawn.js';
import {buildGraphics} from './graphics.js';
let storage;try{storage=window.localStorage;}catch{}
const game=new Game(storage);
const $=id=>document.getElementById(id),engine=new Engine($('game'),true,{preserveDrawingBuffer:true}),scene=new Scene(engine);
scene.clearColor=new Color4(.64,.81,.91,1);scene.fogMode=Scene.FOGMODE_EXP2;scene.fogDensity=.003;scene.fogColor=new Color3(.64,.81,.91);
const ambient=new HemisphericLight('sky',new Vector3(0,1,0),scene);ambient.intensity=.85;ambient.groundColor=new Color3(.25,.31,.15);
const sun=new DirectionalLight('sun',new Vector3(-.65,-1,.5),scene);sun.position=new Vector3(20,35,-20);sun.intensity=1.15;
const shadows=new ShadowGenerator(2048,sun);shadows.usePercentageCloserFiltering=true;shadows.filteringQuality=ShadowGenerator.QUALITY_MEDIUM;shadows.bias=.0005;shadows.normalBias=.035;shadows.darkness=.22;
const lawn=game.lawn;
const visuals=buildGraphics(scene,shadows,lawn);
const {mower,driver,walker,blade,refreshGrass}=visuals;
const camera=new ArcRotateCamera('chase',-Math.PI/2,1.29,5.7,new Vector3(0,1,0),scene);
camera.minZ=.08;camera.fov=1.05;
let keys=new Set(),touch={throttle:0,steer:0},showPerf=false;
const time=v=>v?`${Math.floor(v/60)}:${String(Math.floor(v%60)).padStart(2,'0')}`:'—';
function action(code){if(code==='KeyR')reset();else if(code==='KeyP'||code==='Escape'){if(!game.finished)game.paused=!game.paused;keys.clear();touch={throttle:0,steer:0};}else if(!game.paused&&!game.finished){if(code==='Space')game.mount();if(code==='KeyB')game.blades=!game.blades;if(code==='KeyH')game.highlight=!game.highlight;}if(code==='KeyM'){game.settings.muted=!game.settings.muted;game.saveSettings();}if(code==='KeyQ'){game.settings.quality=['low','medium','high'][(['low','medium','high'].indexOf(game.settings.quality)+1)%3];applyQuality();game.saveSettings();}if(code==='F3')showPerf=!showPerf;}
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','F3'].includes(e.code))e.preventDefault();keys.add(e.code);audioStart();if(!e.repeat)action(e.code);});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();touch={throttle:0,steer:0};game.paused=true;});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();game.paused=true;}});
$('pause').onclick=()=>action('KeyP');$('reset').onclick=reset;for(const [id,code] of [['mount','Space'],['blades','KeyB'],['highlight','KeyH'],['quality','KeyQ'],['sound','KeyM']])$(id).onclick=()=>{audioStart();action(code);};
for(const button of document.querySelectorAll('[data-drive]')){button.addEventListener('pointerdown',e=>{e.preventDefault();button.setPointerCapture(e.pointerId);audioStart();const [axis,value]=button.dataset.drive.split(':');touch[axis]=Number(value);});for(const event of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(event,()=>{touch[button.dataset.drive.split(':')[0]]=0;});}
function applyQuality(){const q=game.settings.quality;engine.setHardwareScalingLevel(q==='low'?1.8:q==='medium'?1.3:1);scene.shadowsEnabled=q!=='low';blade.setEnabled(q!=='low');visuals.setQuality(q);$('quality').textContent='Quality: '+q;}
applyQuality();
function reset(){game.reset();keys.clear();touch={throttle:0,steer:0};refreshGrass(Array.from({length:lawn.cells.length},(_,i)=>i));paintMap();}

// DynamicTexture stays GPU-resident; only update the small cut map after cutting.
const cutTexture=new DynamicTexture('cut map',{width:512,height:512},scene,false);cutTexture.hasAlpha=false;const cutMaterial=new StandardMaterial('directional lawn',scene);cutMaterial.diffuseTexture=cutTexture;cutMaterial.specularColor=Color3.Black();const cutGround=MeshBuilder.CreateGround('directional ground',{width:24,height:30},scene);cutGround.position.y=.015;cutGround.material=cutMaterial;cutGround.receiveShadows=true;
function paintMap(ids=Array.from({length:lawn.cells.length},(_,i)=>i)){
  const ctx=cutTexture.getContext(),size=cutTexture.getSize(),w=size.width/lawn.cols,h=size.height/lawn.rows;
  for(const id of ids){const x=id%lawn.cols*w,y=Math.floor(id/lawn.cols)*h,state=lawn.cells[id];
    ctx.fillStyle=['#557529','#8aa549','#6d8e3b','#807457'][state];ctx.fillRect(x,y,w+.01,h+.01);
    for(let j=0;j<18;j++){const noise=((id*73856093+j*19349663)>>>0);ctx.fillStyle=j%2?'#ffffff13':'#182c1020';ctx.fillRect(x+(noise%997)/997*(w-1),y+((noise>>>10)%991)/991*(h-1),.7,1.5);}
  }
  cutTexture.update();
}paintMap();
const minimap=$('map'),mc=minimap.getContext('2d');function drawMap(){mc.fillStyle='#243323';mc.fillRect(0,0,160,200);for(let id=0;id<lawn.cells.length;id++){const state=lawn.cells[id];mc.fillStyle=state===BLOCKED?'#8c8879':state===0?(game.highlight||lawn.progress>.95?'#dded79':'#4b7132'):state===1?'#9ab955':'#799d45';mc.fillRect(id%lawn.cols*160/lawn.cols,Math.floor(id/lawn.cols)*200/lawn.rows,160/lawn.cols+.2,200/lawn.rows+.2);}const a=game.actor;mc.save();mc.translate((a.x+12)/24*160,(a.z+15)/30*200);mc.rotate(-a.yaw);mc.fillStyle='white';mc.beginPath();mc.moveTo(0,7);mc.lineTo(-5,-5);mc.lineTo(5,-5);mc.closePath();mc.fill();mc.restore();}
let audio,osc,gain;function audioStart(){if(!audio){try{audio=new AudioContext();osc=audio.createOscillator();gain=audio.createGain();osc.type='sawtooth';osc.connect(gain);gain.connect(audio.destination);gain.gain.value=0;osc.start();}catch{}}if(audio?.state==='suspended')audio.resume().catch(()=>{});}
let previousButtons=[];function gamepadInput(){const pad=Array.from(navigator.getGamepads?.()||[]).find(Boolean);if(!pad)return {throttle:0,steer:0};const mapping={0:'Space',1:'KeyB',2:'KeyH',3:'KeyM',9:'KeyP'};for(const [i,code] of Object.entries(mapping)){const pressed=pad.buttons[i]?.pressed;if(pressed&&!previousButtons[i]){audioStart();action(code);}previousButtons[i]=pressed;}const dead=v=>Math.abs(v||0)>.15?v:0;return {throttle:(pad.buttons[7]?.value||0)-(pad.buttons[6]?.value||0)-dead(pad.axes[1]),steer:dead(pad.axes[0])};}
let hudTick=0;engine.runRenderLoop(()=>{const dt=Math.min(engine.getDeltaTime()/1000,.05),pad=gamepadInput();const throttle=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)+touch.throttle+pad.throttle,steer=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+touch.steer+pad.steer;const changed=game.step(dt,{throttle,steer});if(changed.length){refreshGrass(changed);paintMap(changed);}mower.position.set(game.mower.x,0,game.mower.z);mower.rotation.y=game.mower.yaw;driver.setEnabled(game.onMower);visuals.update(game.paused||game.finished?0:dt,game.speed);walker.setEnabled(!game.onMower);walker.position.set(game.walker.x,0,game.walker.z);walker.rotation.y=game.walker.yaw;
const a=game.actor,target=new Vector3(a.x,1,a.z);camera.setTarget(Vector3.Lerp(camera.target,target,1-Math.exp(-5*dt)));camera.alpha=-Math.PI/2-a.yaw;camera.beta=1.32;let distance=game.onMower?5.2:4.5;for(let r=2;r<distance;r+=.25){const cx=a.x-Math.sin(a.yaw)*r*Math.sin(1.32),cz=a.z-Math.cos(a.yaw)*r*Math.sin(1.32);if(Math.abs(cx)>12.5||Math.abs(cz)>15.5){distance=r;break;}}camera.radius=distance;
if(audio){osc.frequency.setTargetAtTime((game.onMower?45:95)+game.measuredSpeed*12,audio.currentTime,.1);gain.gain.setTargetAtTime(game.settings.muted||game.paused||game.finished?0:.018,audio.currentTime,.05);}
hudTick+=dt;if(hudTick>.15){hudTick=0;const objectives=game.lawn.objectives(),names=['Cut the front yard','Cut the side yard','Cut the back yard','Trim around objects'];$('objectives').replaceChildren(...names.map((name,i)=>{const el=document.createElement('div');const check=document.createElement('span');check.className='check'+(objectives[i]>=.97?' done':'');check.textContent=objectives[i]>=.97?'✓':'';el.append(check,document.createTextNode(name));el.title=Math.floor(objectives[i]*100)+'% complete';return el;}));$('percent').textContent=Math.floor(lawn.progress*100)+'%';$('fill').style.width=lawn.progress*100+'%';$('speed').textContent=(game.measuredSpeed*2.237).toFixed(1);$('blade').textContent=game.onMower?(game.blades?'BLADES ON':'BLADES OFF'):'WEED EATER';$('status').textContent=game.finished?game.message:game.paused?'Paused · P or Resume to continue':game.fuel<.2?'Low fuel · stop by the red can':game.onMower?'Mow the open lawn. Hop off for edges.':'Trim the edges. Space near mower to ride.';$('pause').textContent=game.paused?'Resume':'Pause';$('mount').textContent=game.onMower?'Hop off':'Hop on';$('fuel').textContent=Math.round(game.fuel*100)+'% fuel';$('fuel-level').style.height=(game.fuel*100)+'%';$('timer').textContent=time(game.elapsed);$('best').textContent='Best '+time(game.best);$('sound').textContent=game.settings.muted?'Sound off':'Sound on';$('fps').textContent=showPerf?Math.round(engine.getFps())+' FPS · '+game.settings.quality:'';drawMap();}scene.render();});window.addEventListener('resize',()=>engine.resize());
