import {Engine,Scene,Vector3,Color3,Color4,MeshBuilder,StandardMaterial,HemisphericLight,DirectionalLight,ShadowGenerator,ArcRotateCamera,TransformNode,Matrix,Quaternion,DynamicTexture} from '@babylonjs/core';
import './style.css';
import {Game, BLOCKED} from './lawn.js';
let storage;try{storage=window.localStorage;}catch{}
const game=new Game(storage);
const $=id=>document.getElementById(id),engine=new Engine($('game'),true,{preserveDrawingBuffer:true}),scene=new Scene(engine);
scene.clearColor=new Color4(.64,.81,.91,1);scene.fogMode=Scene.FOGMODE_EXP2;scene.fogDensity=.008;scene.fogColor=new Color3(.64,.81,.91);
const ambient=new HemisphericLight('sky',new Vector3(0,1,0),scene);ambient.intensity=.8;ambient.groundColor=new Color3(.25,.31,.15);
const sun=new DirectionalLight('sun',new Vector3(-.65,-1,.5),scene);sun.position=new Vector3(20,35,-20);sun.intensity=1.6;
const shadows=new ShadowGenerator(2048,sun);shadows.useBlurExponentialShadowMap=true;shadows.blurKernel=16;shadows.darkness=.25;
function mat(name,color){const m=new StandardMaterial(name,scene);m.diffuseColor=Color3.FromHexString(color);m.specularColor=new Color3(.08,.08,.08);return m;}
const grass=mat('grass','#568326'),short=mat('cut grass','#79a43b'),orange=mat('paint','#ee761a'),dark=mat('rubber','#252a28'),white=mat('siding','#eee9d8'),wood=mat('cedar','#92734a'),roof=mat('roof','#4b5155'),leaf=mat('foliage','#4e742b'),stone=mat('stone','#c0bca9');
function box(name,w,h,d,x,y,z,m,parent){const o=MeshBuilder.CreateBox(name,{width:w,height:h,depth:d},scene);o.position.set(x,y,z);o.material=m;if(parent)o.parent=parent;o.receiveShadows=true;shadows.addShadowCaster(o);return o;}
box('surroundings',100,.15,100,0,-.18,0,grass);box('lawn',24,.1,30,0,-.06,0,short);
for(let i=0;i<24;i++)box('stripe',1,.012,30,i-11.5,.001,0,mat('stripe'+i,i%2?'#76a23a':'#82ad43'));
for(let x=-13;x<=13;x+=.55){box('fence',.5,2.3,.12,x,1.15,16,wood);box('fence',.5,2.3,.12,x,1.15,-16,wood);}for(let z=-16;z<=16;z+=.55)box('fence',.12,2.3,.5,13,1.15,z,wood);
box('house',8,5,14,-17,2.5,-4,white);const top=box('roof',9,.5,15,-17,5.3,-4,roof);top.rotation.z=-.12;
for(let z=-9;z<=1;z+=5){box('window',.08,2,2,-12.96,3,z,dark);box('window glass',.09,1.7,1.7,-12.9,3,z,mat('glass'+z,'#648998'));}
box('porch',3,.3,10,-11.7,.12,-4,stone);for(let z of [-8,0])box('post',.2,3,.2,-10.5,1.7,z,wood);
box('patio',8,.15,4,4,.03,12,stone);
let seed=42;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
for(let i=0;i<18;i++){const x=i<9?12:-12,z=-14+(i%9)*3.4;box('garden bed',1.3,.16,2,x,.03,z,wood);for(let j=0;j<3;j++){const bush=MeshBuilder.CreateSphere('shrub',{diameter:.8+random()*.4,segments:6},scene);bush.position.set(x+(random()-.5)*.7,.5,z+(random()-.5)*1.3);bush.material=leaf;shadows.addShadowCaster(bush);}}
for(const [x,z] of [[10,8],[10,-10],[-11,9]]){box('trunk',.4,4,.4,x,2,z,wood);for(let j=0;j<5;j++){const crown=MeshBuilder.CreateSphere('tree',{diameter:3.2,segments:8},scene);crown.position.set(x+(random()-.5)*2,4.4+random()*2,z+(random()-.5)*2);crown.material=leaf;shadows.addShadowCaster(crown);}}
const lawn=game.lawn,blade=MeshBuilder.CreateCylinder('grass blades',{diameterTop:0,diameterBottom:.075,height:.55,tessellation:3},scene);blade.material=grass;const count=lawn.cols*lawn.rows*9,matrices=new Float32Array(count*16),positions=[];
for(let id=0;id<lawn.cols*lawn.rows;id++)for(let j=0;j<9;j++){const x=-12+(id%lawn.cols+random())*.5,z=-15+(Math.floor(id/lawn.cols)+random())*.5,h=.7+random()*.7;positions.push([x,z,h]);Matrix.Compose(new Vector3(1,lawn.cells[id]===BLOCKED?0:h,1),Quaternion.RotationAxis(Vector3.Up(),random()*6.28),new Vector3(x,.275*h,z)).copyToArray(matrices,(id*9+j)*16);}
blade.thinInstanceSetBuffer('matrix',matrices,16,false);blade.thinInstanceRefreshBoundingInfo();
const mower=new TransformNode('mower',scene);mower.position.set(0,0,-11);box('deck',1.8,.2,1.3,0,.27,.3,orange,mower);box('body',1.25,.45,1.7,0,.6,0,orange,mower);box('engine',.9,.45,.65,0,.95,-.6,dark,mower);box('seat',.7,.15,.6,0,1.02,-.05,dark,mower);box('seat back',.7,.65,.15,0,1.3,-.35,dark,mower);
for(const x of [-.77,.77])for(const z of [-.55,.65]){const wheel=MeshBuilder.CreateCylinder('wheel',{diameter:z<0?.7:.36,height:.28,tessellation:16},scene);wheel.rotation.z=Math.PI/2;wheel.position.set(x,z<0?.36:.23,z);wheel.material=dark;wheel.parent=mower;shadows.addShadowCaster(wheel);}
const shirt=mat('shirt','#3b5061'),skin=mat('skin','#c89972');box('driver torso',.55,.65,.35,0,1.55,-.02,shirt,mower);const head=MeshBuilder.CreateSphere('driver head',{diameter:.34,segments:12},scene);head.position.set(0,2.04,0);head.parent=mower;head.material=skin;box('cap',.38,.13,.4,0,2.2,0,dark,mower);for(const x of [-.34,.34]){box('arm',.14,.4,.14,x,1.52,.2,skin,mower);box('lever',.07,.5,.07,x,1.13,.4,dark,mower);}
const camera=new ArcRotateCamera('chase',-Math.PI/2,1.12,8,new Vector3(0,1,0),scene);camera.minZ=.1;camera.fov=.85;
const walker=new TransformNode('walker',scene);box('walking torso',.5,.65,.3,0,1.25,0,shirt,walker);const wh=head.clone('walking head');wh.parent=walker;wh.position.set(0,1.75,0);for(const x of [-.16,.16])box('leg',.18,.8,.2,x,.55,0,dark,walker);const shaft=box('trimmer shaft',.04,.04,1.2,.2,.35,.5,stone,walker);shaft.rotation.x=-.3;box('trimmer head',.3,.07,.3,.2,.15,1,dark,walker);box('gas can',.3,.45,.25,-9,.25,-4,mat('red','#c84729'));
let keys=new Set(),touch={throttle:0,steer:0},showPerf=false;
const time=v=>v?`${Math.floor(v/60)}:${String(Math.floor(v%60)).padStart(2,'0')}`:'—';
function action(code){if(code==='KeyR')reset();else if(code==='KeyP'||code==='Escape'){if(!game.finished)game.paused=!game.paused;keys.clear();touch={throttle:0,steer:0};}else if(!game.paused&&!game.finished){if(code==='Space')game.mount();if(code==='KeyB')game.blades=!game.blades;if(code==='KeyH')game.highlight=!game.highlight;}if(code==='KeyM'){game.settings.muted=!game.settings.muted;game.saveSettings();}if(code==='KeyQ'){game.settings.quality=['low','medium','high'][(['low','medium','high'].indexOf(game.settings.quality)+1)%3];applyQuality();game.saveSettings();}if(code==='F3')showPerf=!showPerf;}
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','F3'].includes(e.code))e.preventDefault();keys.add(e.code);audioStart();if(!e.repeat)action(e.code);});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();touch={throttle:0,steer:0};game.paused=true;});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();game.paused=true;}});
$('pause').onclick=()=>action('KeyP');$('reset').onclick=reset;for(const [id,code] of [['mount','Space'],['blades','KeyB'],['highlight','KeyH'],['quality','KeyQ'],['sound','KeyM']])$(id).onclick=()=>{audioStart();action(code);};
for(const button of document.querySelectorAll('[data-drive]')){button.addEventListener('pointerdown',e=>{e.preventDefault();button.setPointerCapture(e.pointerId);audioStart();const [axis,value]=button.dataset.drive.split(':');touch[axis]=Number(value);});for(const event of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(event,()=>{touch[button.dataset.drive.split(':')[0]]=0;});}
function applyQuality(){const q=game.settings.quality;engine.setHardwareScalingLevel(q==='low'?1.8:q==='medium'?1.3:1);scene.shadowsEnabled=q!=='low';blade.setEnabled(q!=='low');$('quality').textContent='Quality: '+q;}
applyQuality();
function refreshGrass(ids){for(const id of ids)for(let j=0;j<9;j++){const i=id*9+j,[x,z,h]=positions[i],state=lawn.cells[id],height=state===BLOCKED?0:state===0?h:.08;Matrix.Compose(new Vector3(1,height,1),Quaternion.Identity(),new Vector3(x,.275*height,z)).copyToArray(matrices,i*16);}blade.thinInstanceBufferUpdated('matrix');}
function reset(){game.reset();keys.clear();touch={throttle:0,steer:0};refreshGrass(Array.from({length:lawn.cells.length},(_,i)=>i));paintMap();}
const groundTexture=document.createElement('canvas');groundTexture.width=lawn.cols;groundTexture.height=lawn.rows;const gc=groundTexture.getContext('2d');
// DynamicTexture stays GPU-resident; only update the small cut map after cutting.
const cutTexture=new DynamicTexture('cut map',{width:lawn.cols,height:lawn.rows},scene,false);cutTexture.hasAlpha=false;const cutMaterial=new StandardMaterial('directional lawn',scene);cutMaterial.diffuseTexture=cutTexture;cutMaterial.specularColor=Color3.Black();const cutGround=MeshBuilder.CreateGround('directional ground',{width:24,height:30},scene);cutGround.position.y=.015;cutGround.material=cutMaterial;cutGround.receiveShadows=true;
function paintMap(){const ctx=cutTexture.getContext();for(let id=0;id<lawn.cells.length;id++){ctx.fillStyle=['#456d27','#84a943','#638537','#807457'][lawn.cells[id]];ctx.fillRect(id%lawn.cols,Math.floor(id/lawn.cols),1,1);}cutTexture.update();}paintMap();
const minimap=$('map'),mc=minimap.getContext('2d');function drawMap(){mc.fillStyle='#243323';mc.fillRect(0,0,160,200);for(let id=0;id<lawn.cells.length;id++){const state=lawn.cells[id];mc.fillStyle=state===BLOCKED?'#8c8879':state===0?(game.highlight||lawn.progress>.95?'#dded79':'#4b7132'):state===1?'#9ab955':'#799d45';mc.fillRect(id%lawn.cols*160/lawn.cols,Math.floor(id/lawn.cols)*200/lawn.rows,160/lawn.cols+.2,200/lawn.rows+.2);}const a=game.actor;mc.save();mc.translate((a.x+12)/24*160,(a.z+15)/30*200);mc.rotate(-a.yaw);mc.fillStyle='white';mc.beginPath();mc.moveTo(0,7);mc.lineTo(-5,-5);mc.lineTo(5,-5);mc.closePath();mc.fill();mc.restore();}
let audio,osc,gain;function audioStart(){if(!audio){try{audio=new AudioContext();osc=audio.createOscillator();gain=audio.createGain();osc.type='sawtooth';osc.connect(gain);gain.connect(audio.destination);gain.gain.value=0;osc.start();}catch{}}if(audio?.state==='suspended')audio.resume().catch(()=>{});}
let previousButtons=[];function gamepadInput(){const pad=Array.from(navigator.getGamepads?.()||[]).find(Boolean);if(!pad)return {throttle:0,steer:0};const mapping={0:'Space',1:'KeyB',2:'KeyH',3:'KeyM',9:'KeyP'};for(const [i,code] of Object.entries(mapping)){const pressed=pad.buttons[i]?.pressed;if(pressed&&!previousButtons[i]){audioStart();action(code);}previousButtons[i]=pressed;}const dead=v=>Math.abs(v||0)>.15?v:0;return {throttle:(pad.buttons[7]?.value||0)-(pad.buttons[6]?.value||0)-dead(pad.axes[1]),steer:dead(pad.axes[0])};}
let hudTick=0;engine.runRenderLoop(()=>{const dt=Math.min(engine.getDeltaTime()/1000,.05),pad=gamepadInput();const throttle=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)+touch.throttle+pad.throttle,steer=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+touch.steer+pad.steer;const changed=game.step(dt,{throttle,steer});if(changed.length){refreshGrass(changed);paintMap();}mower.position.set(game.mower.x,0,game.mower.z);mower.rotation.y=game.mower.yaw;head.setEnabled(game.onMower);for(const mesh of mower.getChildMeshes())if(mesh.name.startsWith('driver')||mesh.name==='cap'||mesh.name==='arm')mesh.setEnabled(game.onMower);walker.setEnabled(!game.onMower);walker.position.set(game.walker.x,0,game.walker.z);walker.rotation.y=game.walker.yaw;
const a=game.actor,target=new Vector3(a.x,1,a.z);camera.setTarget(Vector3.Lerp(camera.target,target,1-Math.exp(-5*dt)));camera.alpha=-Math.PI/2-a.yaw;camera.beta=1.12;let distance=game.onMower?8:5;for(let r=2;r<distance;r+=.25){const cx=a.x-Math.sin(a.yaw)*r*Math.sin(1.12),cz=a.z-Math.cos(a.yaw)*r*Math.sin(1.12);if(Math.abs(cx)>12.5||Math.abs(cz)>15.5){distance=r;break;}}camera.radius=distance;
if(audio){osc.frequency.setTargetAtTime((game.onMower?45:95)+game.measuredSpeed*12,audio.currentTime,.1);gain.gain.setTargetAtTime(game.settings.muted||game.paused||game.finished?0:.018,audio.currentTime,.05);}
hudTick+=dt;if(hudTick>.15){hudTick=0;const objectives=game.lawn.objectives(),names=['Cut the front yard','Cut the side yard','Cut the back yard','Trim around objects'];$('objectives').replaceChildren(...names.map((name,i)=>{const el=document.createElement('div');el.textContent=(objectives[i]>=.97?'✓ ':'○ ')+name+' · '+Math.floor(objectives[i]*100)+'%';return el;}));$('percent').textContent=Math.floor(lawn.progress*100)+'%';$('fill').style.width=lawn.progress*100+'%';$('speed').textContent=(game.measuredSpeed*2.237).toFixed(1);$('blade').textContent=game.onMower?(game.blades?'BLADES ON':'BLADES OFF'):'WEED EATER';$('status').textContent=game.finished?game.message:game.paused?'Paused · P or Resume to continue':game.fuel<.2?'Low fuel · stop by the red can':game.onMower?'Mow the open lawn. Hop off for edges.':'Trim the edges. Space near mower to ride.';$('pause').textContent=game.paused?'Resume':'Pause';$('mount').textContent=game.onMower?'Hop off':'Hop on';$('fuel').textContent=Math.round(game.fuel*100)+'% fuel';$('timer').textContent=time(game.elapsed);$('best').textContent='Best '+time(game.best);$('sound').textContent=game.settings.muted?'Sound off':'Sound on';$('fps').textContent=showPerf?Math.round(engine.getFps())+' FPS · '+game.settings.quality:'';drawMap();}scene.render();});window.addEventListener('resize',()=>engine.resize());
